apiVersion: v1
kind: Service
metadata:
    name: "bsak8snov095mp-f3cb"
    labels:
        app: "bsak8snov095mp-f3cb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "bsak8snov095mp-f3cb"