apiVersion: v1
kind: Service
metadata:
    name: "frgk8s-6c10"
    labels:
        app: "frgk8s-6c10"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "frgk8s-6c10"